#!/bin/sh

LANG=C
export LANG

umask 077

gitfs_list()
{
	user=`whoami`
	curr_year=`date +"%Y"`

	git log --abbrev=7 --pretty="format:^%at %h %s" --graph | sed -e 's/\\/\\/g' |
	awk -F^ -v cy=$curr_year -v ur=$user '{
		px=$1;
		gsub(/\/|\\/, "+", px);
		str="";
		hash="0000000";
		if( length($2) > 0 ) {
			split($2" ", a, " ");
			lastTime=a[1];
			hash=a[2];
			str=substr($2, index($2, hash) + length(hash), length($2));
			str=str".diff";
			delete a;
		}

		cmd="date -d @\""lastTime"\" +\"%Y\"";
		cmd | getline year;
		close(cmd);

		cmd="date -d @\""lastTime"\" +\"%b %d %Y\"";
		if (cy == year)
			cmd="date -d @\""lastTime"\" +\"%b %d %H:%M\"";
		cmd | getline date;
		close(cmd);

		print "-r--r--r--   1 "ur"     0  0 "date" [c:"hash"]"px""str;
	}'
}

gitfs_copyout()
{
    b=`echo \"$3\" | cut -d ':' -f2 | cut -d ']' -f1`
	[ "$b" = "0000000" ] && echo "fork" >> "$4" || git log -1 -p --stat $b >> "$4"	
}

case "$1" in
    list) gitfs_list "$@" ;;
    copyout) gitfs_copyout "$@" ;;
    *) exit 1 ;;
esac
exit 0
